import { createHash } from "node:crypto";
import openapiTS, { astToString } from "openapi-typescript";

export const openapiURL = process.env.BOUNTY_OPENAPI_URL ??
  "https://api.trybounty.ai/openapi.json";

export const snapshotURL = new URL(
  "../packages/agent-sdk/openapi/agent-v1.json",
  import.meta.url,
);

export const generatedURL = new URL(
  "../packages/agent-sdk/src/internal/generated/agent-v1.ts",
  import.meta.url,
);

export const checksumsURL = new URL(
  "./openapi-checksums.json",
  import.meta.url,
);

export function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

export async function fetchOpenAPIContract() {
  const response = await fetch(openapiURL, {
    headers: { accept: "application/json" },
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok) {
    throw new Error(
      `Could not fetch the live Agent OpenAPI contract (${response.status})`,
    );
  }
  return await response.json();
}

export function serializeOpenAPIContract(contract) {
  const serialized = JSON.stringify(contract);
  if (serialized === undefined) {
    throw new Error("The live Agent OpenAPI contract is not JSON serializable");
  }
  return serialized;
}

export async function renderOpenAPITypes(snapshotText) {
  const snapshotHash = sha256(snapshotText);
  const declarations = astToString(
    await openapiTS(Buffer.from(snapshotText)),
  );
  return `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * OpenAPI snapshot SHA-256: ${snapshotHash}
 */

${declarations}`;
}

export function renderOpenAPIChecksums(snapshotText, generatedText) {
  return `${JSON.stringify({
    snapshotSha256: sha256(snapshotText),
    generatedTypesSha256: sha256(generatedText),
  }, null, 2)}\n`;
}
